self.config = {
  "version": "1.0.0.330",
  "pageTitle": "Creations Manager",
  "cookieIdentifier": "creations_manager",
  "foundationYear": 2024,
  "pageDescription": "You can manage your creations with this web app. Add, edit, and delete vehicles, and export your data as JSON.",
  "localhostPath": "/creations-manager",
  "scope": "/creations-manager/",
  "excludedPaths": [],
  "openCookiePopupAtPageLoad": true,
  "showNewUpdateNotes": false,
  "maintenanceModeWithFailedBackend": false,
  "enableInputValidation": true,
  "enableImageComparisonSliders": true,
  "enableInfoBar": false,
  "userLoginEnabled": false,
  "redirect404ToRoot": false,
  "appIcon": "img/app-icons/icon",
  "trustedImageDomains": [],
  "useMouseDown": false,
  "useFlexPopups": true,
  "backNavigationClosesPopups": true,
  "scrollPositionRecallLimit": 20
};